export interface LanguageConfig {
  code: string;
  name: string;
  readmeFileName: string;
  localeFileName: string;
}

export interface Translation {
  title: string;
  subtitle: string;
  copyright: string;
  current: string;
  view: string;
  viewInGallery: string;
  promptLibrary: string;
  modelPage: string;
  stats: string;
  metric: string;
  count: string;
  totalPrompts: string;
  categories: string;
  previewVideos: string;
  lastUpdated: string;
  featuredPrompts: string;
  allPrompts: string;
  description: string;
  prompt: string;
  category: string;
  source: string;
  author: string;
  language: string;
  video: string;
  sourceLink: string;
  browseByCategory: string;
  localUsage: string;
  license: string;
  autoGenerated: string;
}

export const SUPPORTED_LANGUAGES: LanguageConfig[] = [
  { code: "en", name: "English", readmeFileName: "README.md", localeFileName: "en.json" },
  { code: "zh", name: "简体中文", readmeFileName: "i18n/README_zh.md", localeFileName: "zh.json" },
  { code: "zh-TW", name: "繁體中文", readmeFileName: "i18n/README_zh-TW.md", localeFileName: "zh-TW.json" },
  { code: "ja", name: "日本語", readmeFileName: "i18n/README_ja.md", localeFileName: "ja.json" },
  { code: "ko", name: "한국어", readmeFileName: "i18n/README_ko.md", localeFileName: "ko.json" },
  { code: "th", name: "ไทย", readmeFileName: "i18n/README_th.md", localeFileName: "th.json" },
  { code: "vi", name: "Tiếng Việt", readmeFileName: "i18n/README_vi.md", localeFileName: "vi.json" },
  { code: "hi", name: "हिन्दी", readmeFileName: "i18n/README_hi.md", localeFileName: "hi.json" },
  { code: "es", name: "Español", readmeFileName: "i18n/README_es.md", localeFileName: "es.json" },
  { code: "de", name: "Deutsch", readmeFileName: "i18n/README_de.md", localeFileName: "de.json" },
  { code: "fr", name: "Français", readmeFileName: "i18n/README_fr.md", localeFileName: "fr.json" },
  { code: "it", name: "Italiano", readmeFileName: "i18n/README_it.md", localeFileName: "it.json" },
  { code: "pt", name: "Português", readmeFileName: "i18n/README_pt.md", localeFileName: "pt.json" },
  { code: "tr", name: "Türkçe", readmeFileName: "i18n/README_tr.md", localeFileName: "tr.json" },
  { code: "ar", name: "العربية", readmeFileName: "i18n/README_ar.md", localeFileName: "ar.json" },
  { code: "id", name: "Bahasa Indonesia", readmeFileName: "i18n/README_id.md", localeFileName: "id.json" },
  { code: "nl", name: "Nederlands", readmeFileName: "i18n/README_nl.md", localeFileName: "nl.json" },
  { code: "pl", name: "Polski", readmeFileName: "i18n/README_pl.md", localeFileName: "pl.json" },
  { code: "ru", name: "Русский", readmeFileName: "i18n/README_ru.md", localeFileName: "ru.json" },
  { code: "sv", name: "Svenska", readmeFileName: "i18n/README_sv.md", localeFileName: "sv.json" }
];

const en: Translation = {
  title: "Awesome MiniMax H3 Prompts",
  subtitle: "Curated MiniMax H3 video prompts from the official showcase — brand film, motion graphics, narrative, e-commerce, game and industrial cases, each with the real generated preview.",
  copyright: "All prompts are shared for learning, organization, and discovery. Open an issue if anything should be removed.",
  current: "Current",
  view: "View",
  viewInGallery: "View in Atlas Cloud",
  promptLibrary: "Prompt Library",
  modelPage: "Model Page",
  stats: "Statistics",
  metric: "Metric",
  count: "Count",
  totalPrompts: "Total Prompts",
  categories: "Categories",
  previewVideos: "Preview Videos",
  lastUpdated: "Last Updated",
  featuredPrompts: "Featured Prompts",
  allPrompts: "All Prompts",
  description: "Description",
  prompt: "Prompt",
  category: "Category",
  source: "Source",
  author: "Author",
  language: "Language",
  video: "Video",
  sourceLink: "Source Link",
  browseByCategory: "Browse by Category",
  localUsage: "Local Usage",
  license: "License",
  autoGenerated: "This README is auto-generated.",
};

const zh: Translation = {
  ...en,
  title: "MiniMax H3 提示词大全",
  subtitle: "精选 MiniMax H3 官方案例视频提示词——品牌大片、动态图形、剧情、电商、游戏、工业等场景,每条都附真实生成成片。",
  copyright: "所有提示词仅用于学习、整理和检索。如有内容需要移除，请提交 issue。",
  current: "当前",
  view: "查看",
  viewInGallery: "在 Atlas Cloud 查看",
  promptLibrary: "提示词库",
  modelPage: "模型页",
  stats: "统计数据",
  metric: "指标",
  count: "数量",
  totalPrompts: "提示词总数",
  categories: "分类数",
  previewVideos: "预览视频数",
  lastUpdated: "最后更新",
  featuredPrompts: "精选提示词",
  allPrompts: "全部提示词",
  description: "描述",
  prompt: "提示词",
  category: "分类",
  source: "来源",
  author: "作者",
  language: "语言",
  video: "视频",
  sourceLink: "原始链接",
  browseByCategory: "按分类浏览",
  localUsage: "本地使用",
  license: "许可证",
  autoGenerated: "此 README 为自动生成。",
};

const zhTW: Translation = {
  ...zh,
  title: "MiniMax H3 提示詞大全 + MiniMax H3",
  subtitle: "精选 MiniMax H3 官方案例视频提示词——品牌大片、动态图形、剧情、电商、游戏、工业等场景,每条都附真实生成成片。",
  copyright: "所有提示詞僅用於學習、整理與檢索。如有內容需要移除，請提交 issue。",
  current: "目前",
  view: "查看",
  viewInGallery: "在 Atlas Cloud 查看",
  promptLibrary: "提示詞庫",
  modelPage: "模型頁",
  stats: "統計資料",
  metric: "指標",
  count: "數量",
  totalPrompts: "提示詞總數",
  categories: "分類數",
  previewVideos: "預覽影片數",
  lastUpdated: "最後更新",
  featuredPrompts: "精選提示詞",
  allPrompts: "全部提示詞",
  description: "描述",
  prompt: "提示詞",
  category: "分類",
  source: "來源",
  author: "作者",
  language: "語言",
  video: "影片",
  sourceLink: "原始連結",
  browseByCategory: "按分類瀏覽",
  localUsage: "本地使用",
  license: "授權條款",
  autoGenerated: "此 README 為自動生成。",
};

const translations: Record<string, Translation> = {
  en,
  zh,
  "zh-TW": zhTW,
};

export function t<K extends keyof Translation>(key: K, locale: string): Translation[K] {
  return (translations[locale] || translations.en)[key];
}
